name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Auto Assign Issues/PRs
        uses: wow-actions/auto-assign@v3.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            VicHofs
            llamakking
            AnonymousMystic
          numberOfAssignees: 1
          assignees: gopher-tunnels/back-end
          excludeLabels: |
            reading
